package net.minecraft.world.level.lighting;

@:native("net.minecraft.world.level.lighting.SpatialLongSet")
@:mapping("net.minecraft.class_6136")
extern class SpatialLongSet extends it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet
{
  public function new(i:Int, f:Float);
  @:badMapping("unresolvedMethodOverride")
  @:mapping("~~SUPEROVERRIDEFAILED:^it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet#add(long)^it.unimi.dsi.fastutil.longs.AbstractLongSortedSet#add(long)^it.unimi.dsi.fastutil.longs.AbstractLongSet#add(long)^it.unimi.dsi.fastutil.longs.AbstractLongCollection#add(long)^java.util.AbstractCollection#add(long)~~~IFACEOVERRIDEFAILED:^java.io.Serializable#add(long)^java.lang.Cloneable#add(long)^it.unimi.dsi.fastutil.Hash#add(long)^it.unimi.dsi.fastutil.longs.LongSortedSet#add(long)^java.lang.Cloneable#add(long)^it.unimi.dsi.fastutil.longs.LongSet#add(long)^it.unimi.dsi.fastutil.longs.LongCollection#add(long)^java.util.Collection#add(long)^it.unimi.dsi.fastutil.longs.LongSet#add(long)^java.util.SortedSet#add(long)^it.unimi.dsi.fastutil.longs.LongBidirectionalIterable#add(long)^it.unimi.dsi.fastutil.longs.LongCollection#add(long)^java.util.Set#add(long)^java.util.Collection#add(long)^it.unimi.dsi.fastutil.longs.LongIterable#add(long)^java.lang.Iterable#add(long)^it.unimi.dsi.fastutil.longs.LongCollection#add(long)^java.util.Set#add(long)^java.util.Set#add(long)^it.unimi.dsi.fastutil.longs.LongIterable#add(long)^java.util.Collection#add(long)^it.unimi.dsi.fastutil.longs.LongIterable#add(long)^java.util.Collection#add(long)^java.lang.Iterable#add(long)^java.lang.Iterable#add(long)^java.util.Collection#add(long)^it.unimi.dsi.fastutil.longs.LongIterable#add(long)^java.util.Collection#add(long)^java.util.Collection#add(long)^java.lang.Iterable#add(long)^java.lang.Iterable#add(long)^java.lang.Iterable#add(long)^java.lang.Iterable#add(long)^java.lang.Iterable#add(long)^java.lang.Iterable#add(long)^java.lang.Iterable#add(long)^java.lang.Iterable#add(long)")
  public function add(l:Int):Bool;
  @:badMapping("unresolvedMethodOverride")
  @:mapping("~~SUPEROVERRIDEFAILED:^it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet#rem(long)^it.unimi.dsi.fastutil.longs.AbstractLongSortedSet#rem(long)^it.unimi.dsi.fastutil.longs.AbstractLongSet#rem(long)^it.unimi.dsi.fastutil.longs.AbstractLongCollection#rem(long)^java.util.AbstractCollection#rem(long)~~~IFACEOVERRIDEFAILED:^java.io.Serializable#rem(long)^java.lang.Cloneable#rem(long)^it.unimi.dsi.fastutil.Hash#rem(long)^it.unimi.dsi.fastutil.longs.LongSortedSet#rem(long)^java.lang.Cloneable#rem(long)^it.unimi.dsi.fastutil.longs.LongSet#rem(long)^it.unimi.dsi.fastutil.longs.LongCollection#rem(long)^java.util.Collection#rem(long)^it.unimi.dsi.fastutil.longs.LongSet#rem(long)^java.util.SortedSet#rem(long)^it.unimi.dsi.fastutil.longs.LongBidirectionalIterable#rem(long)^it.unimi.dsi.fastutil.longs.LongCollection#rem(long)^java.util.Set#rem(long)^java.util.Collection#rem(long)^it.unimi.dsi.fastutil.longs.LongIterable#rem(long)^java.lang.Iterable#rem(long)^it.unimi.dsi.fastutil.longs.LongCollection#rem(long)^java.util.Set#rem(long)^java.util.Set#rem(long)^it.unimi.dsi.fastutil.longs.LongIterable#rem(long)^java.util.Collection#rem(long)^it.unimi.dsi.fastutil.longs.LongIterable#rem(long)^java.util.Collection#rem(long)^java.lang.Iterable#rem(long)^java.lang.Iterable#rem(long)^java.util.Collection#rem(long)^it.unimi.dsi.fastutil.longs.LongIterable#rem(long)^java.util.Collection#rem(long)^java.util.Collection#rem(long)^java.lang.Iterable#rem(long)^java.lang.Iterable#rem(long)^java.lang.Iterable#rem(long)^java.lang.Iterable#rem(long)^java.lang.Iterable#rem(long)^java.lang.Iterable#rem(long)^java.lang.Iterable#rem(long)^java.lang.Iterable#rem(long)")
  public function rem(l:Int):Bool;
  @:badMapping("unresolvedMethodOverride")
  @:mapping("~~SUPEROVERRIDEFAILED:^it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet#removeFirstLong()^it.unimi.dsi.fastutil.longs.AbstractLongSortedSet#removeFirstLong()^it.unimi.dsi.fastutil.longs.AbstractLongSet#removeFirstLong()^it.unimi.dsi.fastutil.longs.AbstractLongCollection#removeFirstLong()^java.util.AbstractCollection#removeFirstLong()~~~IFACEOVERRIDEFAILED:^java.io.Serializable#removeFirstLong()^java.lang.Cloneable#removeFirstLong()^it.unimi.dsi.fastutil.Hash#removeFirstLong()^it.unimi.dsi.fastutil.longs.LongSortedSet#removeFirstLong()^java.lang.Cloneable#removeFirstLong()^it.unimi.dsi.fastutil.longs.LongSet#removeFirstLong()^it.unimi.dsi.fastutil.longs.LongCollection#removeFirstLong()^java.util.Collection#removeFirstLong()^it.unimi.dsi.fastutil.longs.LongSet#removeFirstLong()^java.util.SortedSet#removeFirstLong()^it.unimi.dsi.fastutil.longs.LongBidirectionalIterable#removeFirstLong()^it.unimi.dsi.fastutil.longs.LongCollection#removeFirstLong()^java.util.Set#removeFirstLong()^java.util.Collection#removeFirstLong()^it.unimi.dsi.fastutil.longs.LongIterable#removeFirstLong()^java.lang.Iterable#removeFirstLong()^it.unimi.dsi.fastutil.longs.LongCollection#removeFirstLong()^java.util.Set#removeFirstLong()^java.util.Set#removeFirstLong()^it.unimi.dsi.fastutil.longs.LongIterable#removeFirstLong()^java.util.Collection#removeFirstLong()^it.unimi.dsi.fastutil.longs.LongIterable#removeFirstLong()^java.util.Collection#removeFirstLong()^java.lang.Iterable#removeFirstLong()^java.lang.Iterable#removeFirstLong()^java.util.Collection#removeFirstLong()^it.unimi.dsi.fastutil.longs.LongIterable#removeFirstLong()^java.util.Collection#removeFirstLong()^java.util.Collection#removeFirstLong()^java.lang.Iterable#removeFirstLong()^java.lang.Iterable#removeFirstLong()^java.lang.Iterable#removeFirstLong()^java.lang.Iterable#removeFirstLong()^java.lang.Iterable#removeFirstLong()^java.lang.Iterable#removeFirstLong()^java.lang.Iterable#removeFirstLong()^java.lang.Iterable#removeFirstLong()")
  public function removeFirstLong():Int;
  @:badMapping("unresolvedMethodOverride")
  @:mapping("~~SUPEROVERRIDEFAILED:^it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet#size()^it.unimi.dsi.fastutil.longs.AbstractLongSortedSet#size()^it.unimi.dsi.fastutil.longs.AbstractLongSet#size()^it.unimi.dsi.fastutil.longs.AbstractLongCollection#size()^java.util.AbstractCollection#size()~~~IFACEOVERRIDEFAILED:^java.io.Serializable#size()^java.lang.Cloneable#size()^it.unimi.dsi.fastutil.Hash#size()^it.unimi.dsi.fastutil.longs.LongSortedSet#size()^java.lang.Cloneable#size()^it.unimi.dsi.fastutil.longs.LongSet#size()^it.unimi.dsi.fastutil.longs.LongCollection#size()^java.util.Collection#size()^it.unimi.dsi.fastutil.longs.LongSet#size()^java.util.SortedSet#size()^it.unimi.dsi.fastutil.longs.LongBidirectionalIterable#size()^it.unimi.dsi.fastutil.longs.LongCollection#size()^java.util.Set#size()^java.util.Collection#size()^it.unimi.dsi.fastutil.longs.LongIterable#size()^java.lang.Iterable#size()^it.unimi.dsi.fastutil.longs.LongCollection#size()^java.util.Set#size()^java.util.Set#size()^it.unimi.dsi.fastutil.longs.LongIterable#size()^java.util.Collection#size()^it.unimi.dsi.fastutil.longs.LongIterable#size()^java.util.Collection#size()^java.lang.Iterable#size()^java.lang.Iterable#size()^java.util.Collection#size()^it.unimi.dsi.fastutil.longs.LongIterable#size()^java.util.Collection#size()^java.util.Collection#size()^java.lang.Iterable#size()^java.lang.Iterable#size()^java.lang.Iterable#size()^java.lang.Iterable#size()^java.lang.Iterable#size()^java.lang.Iterable#size()^java.lang.Iterable#size()^java.lang.Iterable#size()")
  public function size():Int;
  @:badMapping("unresolvedMethodOverride")
  @:mapping("~~SUPEROVERRIDEFAILED:^it.unimi.dsi.fastutil.longs.LongLinkedOpenHashSet#isEmpty()^it.unimi.dsi.fastutil.longs.AbstractLongSortedSet#isEmpty()^it.unimi.dsi.fastutil.longs.AbstractLongSet#isEmpty()^it.unimi.dsi.fastutil.longs.AbstractLongCollection#isEmpty()^java.util.AbstractCollection#isEmpty()~~~IFACEOVERRIDEFAILED:^java.io.Serializable#isEmpty()^java.lang.Cloneable#isEmpty()^it.unimi.dsi.fastutil.Hash#isEmpty()^it.unimi.dsi.fastutil.longs.LongSortedSet#isEmpty()^java.lang.Cloneable#isEmpty()^it.unimi.dsi.fastutil.longs.LongSet#isEmpty()^it.unimi.dsi.fastutil.longs.LongCollection#isEmpty()^java.util.Collection#isEmpty()^it.unimi.dsi.fastutil.longs.LongSet#isEmpty()^java.util.SortedSet#isEmpty()^it.unimi.dsi.fastutil.longs.LongBidirectionalIterable#isEmpty()^it.unimi.dsi.fastutil.longs.LongCollection#isEmpty()^java.util.Set#isEmpty()^java.util.Collection#isEmpty()^it.unimi.dsi.fastutil.longs.LongIterable#isEmpty()^java.lang.Iterable#isEmpty()^it.unimi.dsi.fastutil.longs.LongCollection#isEmpty()^java.util.Set#isEmpty()^java.util.Set#isEmpty()^it.unimi.dsi.fastutil.longs.LongIterable#isEmpty()^java.util.Collection#isEmpty()^it.unimi.dsi.fastutil.longs.LongIterable#isEmpty()^java.util.Collection#isEmpty()^java.lang.Iterable#isEmpty()^java.lang.Iterable#isEmpty()^java.util.Collection#isEmpty()^it.unimi.dsi.fastutil.longs.LongIterable#isEmpty()^java.util.Collection#isEmpty()^java.util.Collection#isEmpty()^java.lang.Iterable#isEmpty()^java.lang.Iterable#isEmpty()^java.lang.Iterable#isEmpty()^java.lang.Iterable#isEmpty()^java.lang.Iterable#isEmpty()^java.lang.Iterable#isEmpty()^java.lang.Iterable#isEmpty()^java.lang.Iterable#isEmpty()")
  public function isEmpty():Bool;
}
