package net.minecraft.world.level.levelgen.feature;

/**
 * This feature generates part of the icebergs found in frozen oceans.
 *  Specifically, it generates tall, triangular prism icebergs, and "donut" or torus shaped icebergs.
 *  Other icebergs are generated by the frozen ocean surface builder instead.
 */
@:native("net.minecraft.world.level.levelgen.feature.IcebergFeature")
@:mapping("net.minecraft.class_3074")
extern class IcebergFeature extends net.minecraft.world.level.levelgen.feature.Feature<net.minecraft.world.level.levelgen.feature.configurations.BlockStateConfiguration>
{
  public function new(codec:com.mojang.serialization.Codec<net.minecraft.world.level.levelgen.feature.configurations.BlockStateConfiguration>);
  @:mapping("method_13151")
  public function place(context:net.minecraft.world.level.levelgen.feature.FeaturePlaceContext<net.minecraft.world.level.levelgen.feature.configurations.BlockStateConfiguration>):Bool;
}
